---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  labels:
    app.kubernetes.io/name: spring-petclinic
    app.kubernetes.io/instance: spring-petclinic
    app_name: spring-petclinic
    app.kubernetes.io/version: "0.0.1"
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-petclinic
      app.kubernetes.io/instance: spring-petclinic
      app_name: spring-petclinic
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-petclinic
        app.kubernetes.io/instance: spring-petclinic
        app_name: spring-petclinic
    spec:    
      serviceAccountName: spring-petclinic
      containers:
        - name: spring-petclinic
          image: DOCKER_IMAGE
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          resources:
            limits:
              memory: 1000Mi
            requests:
              cpu: 1000m
              memory: 1000Mi


