name: Spring_Petclinic CI/CD
on: 
  push: 
    branches: [ "main" ]

jobs:
  Spring_Petclinic:
   
  
    name: Build Docker Image
    runs-on: ubuntu-latest  
    steps:  
        - name: Checkout
          uses: actions/checkout@v2  

        - name: Set short git commit SHA
          id: commit
          uses: prompt/actions-commit-hash@v2  
          
        - name: Login to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Login to Azure Container Registry
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.ACR_LOGIN_SERVER }}
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}
          

        - name: Build, tag, and push image to Azure Container Registry
          env:
            ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
            ACR_REPOSITORY: ${{ secrets.ACR_REPOSITORY }}        
            IMAGE_TAG: ${{ steps.commit.outputs.short }}
          run: |
            docker build -t $ACR_LOGIN_SERVER/$ACR_REPOSITORY:$IMAGE_TAG  .
            docker push $ACR_LOGIN_SERVER/$ACR_REPOSITORY:$IMAGE_TAG

